# Hexo Configuration
## Docs: http://zespia.tw/hexo/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site

##网站标题
title: wessmrs' bok-choy's gree house
##网站副标题
subtitle: 我想让我的生活尽可能变得简单，不用为做太多决定而费神。 -马克·扎克伯格
##网站描述
description: 生活就像所有美好的东西一样，通过不断的努力、不断的练习才能达到你对它的期待。 -马克·扎克伯格
##文章作者
author: wess.mrs
##使用的邮箱
email: wess.mrs@gmail.com
##网站使用的语言
language: 
##所在时区
timezone:

# URL

##站点链接
url: http://wessmrs.com
##网站根目录
root: /
##文章链接格式
permalink: posts/:category/:title.html
##标签文件夹
tag_dir: tags
##归档文件夹
archive_dir: archives
##分类文件夹
category_dir: categories
##code文件夹
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Directory

##资源文件夹，存放内容
source_dir: source
##公共文件夹，存放站点文件
public_dir: public

# Writing

##新文章的文件名称
new_post_name: :title.md
##预设布局
default_layout: post
##中英文间+空格
auto_spacing: false
##标题转换小写
titlecase: false
##在新标签页打开链接
external_link: true
max_open_file: 100
multi_thread: true
##文件名称转换，1小写2大写
filename_case: 0
##显示草稿
render_drafts: false
##启动Asset文件夹
post_asset_folder: false
##代码块的设置
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag

##默认分类
default_category: uncategorized
##分类别名
category_map:
##标签别名
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/

##日期格式
date_format: MMM D YYYY
##时间格式
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes

##当前主题
#believe、gal、rexo、【typing】、yelee、clean-blog、landscape
#solar、【typography】、empty-light、maupassant、sw-blog、xups
theme: typing
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html

##部署部分的设置
deploy:
  type: git
  repo: git@github.com:wessmrs/wessmrs.github.io.git
  branch: master